-- ============================================================================
-- Insaf Mart — Postgres schema for Supabase
--
-- HOW TO RUN
--   1. Supabase dashboard -> your project -> SQL Editor -> New query.
--   2. Paste this whole file and press Run. It is idempotent
--      (`create table if not exists`), so it is safe to re-run.
--   3. Then run `supabase/seed.sql` the same way to load the 5 categories and
--      the 52 catalog rows (3 gift combos + 49 products).
--   4. Copy Project URL + `service_role` key from Settings -> API into
--      `SUPABASE_URL` / `SUPABASE_SERVICE_ROLE_KEY`.
--
-- SECURITY MODEL
--   Row Level Security is enabled on every table and NO policies are created.
--   That is deliberate: the storefront never talks to Supabase from the
--   browser. Every read and write goes through the Next.js route handlers in
--   `app/api/**`, which use the service-role key (`lib/supabase.ts`). The
--   service role bypasses RLS, while the anon/publishable key — the only key
--   that could ever leak to a client — can read and write nothing. So no public
--   policies are needed, and adding one would widen the surface for no gain.
--
-- SHAPE NOTES (parity with the reference Express + SQLite build)
--   * Boolean-ish columns stay integer 0/1 (`is_admin`, `is_verified`,
--     `featured`, `is_combo`, `consumed`) so the JSON the API emits is
--     byte-identical to the Drizzle/SQLite version.
--   * `images`, `tags`, `variants` and `orders.items` are jsonb arrays; the
--     SQLite build stored them as JSON strings and parsed on read.
--   * `otp_codes.expires_at` is epoch milliseconds (bigint), as in the
--     reference.
--   * Money is stored in whole BDT (integer), never a float.
-- ============================================================================

-- ---------------------------------- users ---------------------------------- --

create table if not exists users (
  id            bigint generated by default as identity primary key,
  email         text        not null unique,
  name          text        not null,
  phone         text,
  address       text,
  password_hash text,
  is_verified   integer     not null default 0,
  is_admin      integer     not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists idx_users_email on users (email);
create index if not exists idx_users_is_admin on users (is_admin);

-- -------------------------------- otp_codes -------------------------------- --

create table if not exists otp_codes (
  id         bigint generated by default as identity primary key,
  email      text    not null,
  code       text    not null,
  -- epoch milliseconds, matching the reference implementation
  expires_at bigint  not null,
  consumed   integer not null default 0
);

create index if not exists idx_otp_email on otp_codes (email);
create index if not exists idx_otp_email_code on otp_codes (email, code);

-- --------------------------------- sessions -------------------------------- --

create table if not exists sessions (
  token      text        primary key,
  user_id    bigint      not null references users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_sessions_user on sessions (user_id);

-- -------------------------------- categories ------------------------------- --
-- Storefront category metadata (the reference kept this in `server/catalog.ts`).

create table if not exists categories (
  id         bigint generated by default as identity primary key,
  slug       text    not null unique,
  label      text    not null,
  tagline    text    not null,
  blurb      text    not null,
  image      text    not null,
  sort_order integer not null default 0
);

create index if not exists idx_categories_slug on categories (slug);

-- --------------------------------- products -------------------------------- --

create table if not exists products (
  id            bigint generated by default as identity primary key,
  slug          text        not null unique,
  title         text        not null,
  category      text        not null,
  collection    text,
  description   text        not null,
  price         integer     not null,
  compare_price integer,
  stock         integer     not null default 0,
  -- root-relative image paths, e.g. ["/images/royal-attar-box.webp"]
  images        jsonb       not null default '[]'::jsonb,
  tags          jsonb       not null default '[]'::jsonb,
  -- variant labels, e.g. ["3 ml","6 ml","12 ml"]; a "+৳600" suffix is a surcharge
  variants      jsonb       not null default '[]'::jsonb,
  featured      integer     not null default 0,
  is_combo      integer     not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists idx_products_slug on products (slug);
create index if not exists idx_products_category on products (category);
create index if not exists idx_products_featured on products (featured desc, id);

-- ---------------------------------- orders --------------------------------- --

create table if not exists orders (
  id             bigint generated by default as identity primary key,
  order_number   text        not null unique,      -- IM-YYMMDD-NNNN
  user_id        bigint      references users (id) on delete set null,
  customer_name  text        not null,
  email          text        not null,
  phone          text        not null,
  address        text        not null,
  city           text        not null,
  area           text,
  notes          text,
  -- 'cod' | 'bkash' | 'nagad'
  payment_method text        not null,
  transaction_id text,
  sender_number  text,
  subtotal       integer     not null,
  shipping       integer     not null,
  total          integer     not null,
  -- pending_verification | pending | confirmed | shipped | delivered
  --   | rejected | cancelled
  status         text        not null,
  -- OrderItem[] priced server-side at checkout
  items          jsonb       not null default '[]'::jsonb,
  admin_note     text,
  created_at     timestamptz not null default now(),
  verified_at    timestamptz
);

create index if not exists idx_orders_order_number on orders (order_number);
create index if not exists idx_orders_email on orders (email);
create index if not exists idx_orders_status on orders (status);
create index if not exists idx_orders_created_at on orders (created_at desc);

-- -------------------------------- order_items ------------------------------ --
-- The API keeps the authoritative line items in `orders.items` (jsonb), exactly
-- as the reference does. This normalised mirror exists for SQL reporting —
-- best-sellers, stock planning — and is written alongside the order.

create table if not exists order_items (
  id         bigint generated by default as identity primary key,
  order_id   bigint  not null references orders (id) on delete cascade,
  product_id bigint,
  slug       text    not null,
  title      text    not null,
  price      integer not null,   -- unit price incl. variant surcharge
  quantity   integer not null,
  variant    text,
  image      text
);

create index if not exists idx_order_items_order on order_items (order_id);
create index if not exists idx_order_items_product on order_items (product_id);

-- ------------------------------------ RLS ---------------------------------- --
-- Enabled with no policies: service-role route handlers only (see header).

alter table users       enable row level security;
alter table otp_codes   enable row level security;
alter table sessions    enable row level security;
alter table categories  enable row level security;
alter table products    enable row level security;
alter table orders      enable row level security;
alter table order_items enable row level security;
