-- Insaf Mart — seed data (5 categories + 52 catalog rows: 3 gift combos + 49 products).
--
-- GENERATED FILE — do not edit by hand.
-- Produced by `scripts/generate-seed.py` from `scripts/catalog.json`,
-- which is a JSON dump of the reference `server/catalog.ts`.
--
-- How to run: Supabase dashboard -> SQL Editor -> New query -> paste this file
-- -> Run. Run `supabase/schema.sql` first. Re-running is safe: every statement
-- is idempotent on the natural key (categories.slug / products.slug).

begin;

-- ------------------------------- categories ------------------------------- --

insert into categories (id, slug, label, tagline, blurb, image, sort_order) values
  (1, 'fragrance', 'Fragrance & Attar', 'Oud, musk and amber — bottled by hand', 'Alcohol-free attar oils, roll-on perfume, body mists and bakhoor sourced for depth and longevity.', '/images/cat-fragrance.webp', 1),
  (2, 'skincare', 'Skincare & Beauty', 'Korean-grade care, everyday glow', 'Sunscreen, serums, moisturiser and lip colour chosen for Bangladeshi weather and skin tones.', '/images/cat-skincare.webp', 2),
  (3, 'haircare', 'Hair Care & Accessories', 'Silk, satin and gentle styling', 'Silk scrunchies, satin bonnets, claw clips and heatless styling sets that protect your hair.', '/images/cat-haircare.webp', 3),
  (4, 'fashion', 'Fashion & Lifestyle', 'Anti-tarnish, everyday elegance', 'Anti-tarnish jewellery, canvas totes, mini purses and card holders built to last past one season.', '/images/cat-fashion.webp', 4),
  (5, 'gifts', 'Accessories & Gift', 'Boxed, wrapped, ready to give', 'Curated gift boxes, jewellery, makeup tools and organisers — including Under ৳499 and Under ৳999 sets.', '/images/cat-gifts.webp', 5)
on conflict (slug) do update set
  label = excluded.label,
  tagline = excluded.tagline,
  blurb = excluded.blurb,
  image = excluded.image,
  sort_order = excluded.sort_order;

select setval(pg_get_serial_sequence('categories', 'id'), coalesce((select max(id) from categories), 1));

-- --------------------------------- products -------------------------------- --
-- Order matches the reference seed exactly (combos first, then products), so
-- product ids line up 1:1 with the Express/SQLite build.

insert into products
  (id, slug, title, category, collection, description, price, compare_price,
   stock, images, tags, variants, featured, is_combo)
values
  (1, 'royal-attar-box', 'Royal Attar Box', 'fragrance', 'Gift Combo', 'Our signature presentation box holding premium attar in miniature glass bottles — choose the 3-flavour or 5-flavour set. Includes Cambodian Oud, White Musk and Amber Noir as standard; the 5-flavour set adds Royal Rose and Sandal Wood. Each bottle is alcohol-free, long-lasting perfume oil, sealed with a glass dipper and presented on a maroon velvet tray inside a rigid ivory box.', 1690, 2150, 24, '["/images/royal-attar-box.webp"]'::jsonb, '["attar", "gift box", "oud", "musk", "amber", "royal", "combo", "eid"]'::jsonb, '["3 Flavours", "5 Flavours (+৳600)"]'::jsonb, 1, 1),
  (2, 'couple-box', 'Couple Box', 'fragrance', 'Gift Combo', 'One gents attar and one ladies roll-on perfume oil, paired in a single gift box. The gents side carries a warm oud-and-amber blend; the ladies side is a soft alcohol-free floral musk roll-on that sits close to the skin. Finished with a handwritten card slot — the most requested anniversary and wedding gift we stock.', 1290, 1600, 30, '["/images/couple-box.webp"]'::jsonb, '["couple", "gift box", "attar", "roll on", "perfume", "anniversary", "combo", "wedding"]'::jsonb, '["Classic Pair", "Premium Pair"]'::jsonb, 1, 1),
  (3, 'daily-glow-combo', 'Daily Glow Combo', 'skincare', 'Gift Combo', 'A three-step everyday routine in one box: Korean SPF 50+ sunscreen, a buildable lip tint, and a pure silk scrunchie. Built for the daily commute — sun protection, a wash of colour, and a hair tie that does not crease. Comes in a slim ivory box that fits a tote.', 1150, 1420, 36, '["/images/daily-glow-combo.webp"]'::jsonb, '["combo", "sunscreen", "lip tint", "scrunchie", "glow", "daily", "gift box", "skincare"]'::jsonb, '["Rose Tint", "Coral Tint"]'::jsonb, 1, 1),
  (4, 'cambodian-oud-attar', 'Cambodian Oud Attar', 'fragrance', 'Gents Attar', 'A deep, resinous Cambodian oud with a smoky opening that settles into warm woods and a faint sweetness. Alcohol-free perfume oil, so a single dab on the wrist lasts through the day and into evening prayers. Supplied in a glass roll-top bottle with dipper.', 890, 1150, 42, '["/images/cambodian-oud-attar.webp"]'::jsonb, '["oud", "attar", "gents", "woody", "smoky", "premium", "alcohol free"]'::jsonb, '["3 ml", "6 ml", "12 ml"]'::jsonb, 1, 0),
  (5, 'white-musk-attar', 'White Musk Attar', 'fragrance', 'Gents Attar', 'Clean, powdery white musk — the safest choice if you are new to attar. Soft enough for the office, warm enough for Jummah. Alcohol-free oil that sits close to the skin and never turns sharp.', 650, 820, 58, '["/images/white-musk-attar.webp"]'::jsonb, '["musk", "attar", "gents", "clean", "soft", "everyday", "alcohol free"]'::jsonb, '["3 ml", "6 ml", "12 ml"]'::jsonb, 1, 0),
  (6, 'amber-noir-attar', 'Amber Noir Attar', 'fragrance', 'Gents Attar', 'Golden amber over vanilla and a dry tobacco base. Sweet but not cloying, and the projection is generous — best used sparingly in the warmer months. Alcohol-free perfume oil in a faceted glass bottle.', 790, NULL, 35, '["/images/amber-noir-attar.webp"]'::jsonb, '["amber", "attar", "gents", "sweet", "vanilla", "warm", "winter"]'::jsonb, '["3 ml", "6 ml", "12 ml"]'::jsonb, 0, 0),
  (7, 'rose-musk-rollon', 'Rose Musk Roll-On Perfume Oil', 'fragrance', 'Ladies Roll-On', 'Alcohol-free roll-on perfume oil built around Taif rose softened with white musk. The steel rollerball glides cold on the skin and the scent stays a quiet arm''s-length halo rather than filling a room. Handbag-sized.', 520, 640, 64, '["/images/rose-musk-rollon.webp"]'::jsonb, '["roll on", "ladies", "rose", "musk", "perfume oil", "alcohol free", "floral"]'::jsonb, '["6 ml", "10 ml"]'::jsonb, 1, 0),
  (8, 'jasmine-oud-rollon', 'Jasmine Oud Roll-On Perfume Oil', 'fragrance', 'Ladies Roll-On', 'Night-blooming jasmine laid over a light oud base — floral at first, quietly woody after an hour. Alcohol-free roll-on, so it is gentle on sensitive skin and safe to reapply.', 560, NULL, 48, '["/images/jasmine-oud-rollon.webp"]'::jsonb, '["roll on", "ladies", "jasmine", "oud", "perfume oil", "alcohol free", "floral"]'::jsonb, '["6 ml", "10 ml"]'::jsonb, 0, 0),
  (9, 'velvet-body-mist', 'Velvet Body Mist', 'fragrance', 'Body Mist', 'A fine-spray body mist in soft peony and vanilla, light enough to layer over attar or wear alone after a shower. 250 ml bottle with a locking collar so it will not leak in a bag.', 480, 590, 52, '["/images/velvet-body-mist.webp"]'::jsonb, '["body mist", "spray", "peony", "vanilla", "light", "fresh", "ladies"]'::jsonb, '["250 ml"]'::jsonb, 0, 0),
  (10, 'oud-room-car-spray', 'Oud Room & Car Freshener Spray', 'fragrance', 'Home Fragrance', 'Concentrated oud-and-amber air spray for rooms, wardrobes and car interiors. Two pumps hold for hours, and the formula is water-based so it will not stain upholstery. Comes with a hanging felt tag you can spray for a slow release.', 420, NULL, 70, '["/images/oud-room-car-spray.webp"]'::jsonb, '["room spray", "car freshener", "oud", "home", "air freshener", "amber"]'::jsonb, '["100 ml", "250 ml"]'::jsonb, 0, 0),
  (11, 'bakhoor-burner-set', 'Bakhoor & Burner Set', 'fragrance', 'Home Fragrance', 'A ceramic electric burner paired with 40 g of hand-rolled bakhoor chips in oud and saffron. No charcoal and no smoke alarm — the plate warms the chips gently so the scent fills the room in minutes. Ideal for Thursday evenings and guest arrivals.', 1350, 1690, 18, '["/images/bakhoor-burner-set.webp"]'::jsonb, '["bakhoor", "burner", "oud", "home", "incense", "electric", "gift", "saffron"]'::jsonb, '["Ivory Ceramic", "Charcoal Ceramic"]'::jsonb, 1, 0),
  (12, 'korean-sunscreen-spf50', 'Korean Sunscreen SPF 50+ PA++++', 'skincare', 'Sun Care', 'A lightweight chemical sunscreen that finishes matte with no white cast — tested through Dhaka humidity. SPF 50+ PA++++ with niacinamide and panthenol, so it doubles as the last step of a morning routine. 50 ml tube.', 890, 1100, 46, '["/images/korean-sunscreen-spf50.webp"]'::jsonb, '["sunscreen", "spf", "korean", "skincare", "matte", "no white cast", "spf 50"]'::jsonb, '["50 ml"]'::jsonb, 1, 0),
  (13, 'glow-vitamin-c-serum', 'Glowing Face Serum — 10% Vitamin C', 'skincare', 'Serums', 'A stabilised 10% vitamin C serum with ferulic acid for brightness and even tone. Thin, fast-absorbing, and low enough in concentration to use daily without stinging. Amber glass dropper bottle keeps it from oxidising. 30 ml.', 950, 1250, 40, '["/images/glow-vitamin-c-serum.webp"]'::jsonb, '["serum", "vitamin c", "glow", "brightening", "skincare", "face", "korean"]'::jsonb, '["30 ml"]'::jsonb, 1, 0),
  (14, 'ceramide-moisturizer', 'Ceramide Barrier Moisturiser', 'skincare', 'Moisturisers', 'A gel-cream with ceramides and hyaluronic acid that hydrates without the heavy film. Sits well under sunscreen and makeup, and calms the tightness that follows a strong cleanser. Fragrance-free. 50 ml jar.', 780, NULL, 44, '["/images/ceramide-moisturizer.webp"]'::jsonb, '["moisturizer", "ceramide", "hydration", "skincare", "gel cream", "fragrance free"]'::jsonb, '["50 ml"]'::jsonb, 0, 0),
  (15, 'glossy-lip-oil', 'Glossy Lip Oil', 'skincare', 'Lips', 'A non-sticky lip oil in a sheer wash of colour, with jojoba and vitamin E for overnight repair. The doe-foot applicator carries just enough product, and the finish is glass-glossy rather than tacky.', 390, 480, 72, '["/images/glossy-lip-oil.webp"]'::jsonb, '["lip oil", "glossy", "lips", "beauty", "makeup", "hydrating", "tint"]'::jsonb, '["Clear", "Peach", "Berry"]'::jsonb, 1, 0),
  (16, 'matte-lipstick', 'Velvet Matte Lipstick', 'skincare', 'Lips', 'Full-coverage matte in one pass, with a soft powder finish that does not crack over dry lips. Transfer-resistant enough for a mask, and the bullet is wide enough to line the lip without a pencil.', 450, NULL, 66, '["/images/matte-lipstick.webp"]'::jsonb, '["lipstick", "matte", "lips", "makeup", "beauty", "long lasting"]'::jsonb, '["Maroon Noir", "Nude Rose", "Brick Red"]'::jsonb, 0, 0),
  (17, 'water-lip-tint', 'Water Lip Tint', 'skincare', 'Lips', 'A watery Korean-style tint that stains rather than coats — the colour stays after tea and the lips still feel bare. Build it up for a full lip or blot it once for a just-bitten wash.', 340, 420, 80, '["/images/water-lip-tint.webp"]'::jsonb, '["lip tint", "korean", "lips", "stain", "makeup", "beauty", "water tint"]'::jsonb, '["Cherry", "Rose", "Coral"]'::jsonb, 0, 0),
  (18, 'sheet-mask-set', 'Face Sheet Mask Set — 10 Pieces', 'skincare', 'Masks', 'Ten single-use sheet masks across five varieties: hyaluronic acid, green tea, rice, centella and vitamin C. Cotton-cupra sheets hold serum without sliding off. Keep a few in the fridge for the hot months.', 690, 890, 38, '["/images/sheet-mask-set.webp"]'::jsonb, '["sheet mask", "face mask", "korean", "skincare", "set", "hydrating", "10 pcs"]'::jsonb, '["10 Pieces"]'::jsonb, 0, 0),
  (19, 'silk-scrunchie-set', 'Pure Silk Scrunchie Set — 3 Pieces', 'haircare', 'Scrunchies', 'Three 100% mulberry silk scrunchies in ivory, maroon and charcoal. Silk slides against the hair instead of gripping it, so you avoid the dent and the breakage a rubber band leaves. Hand-stitched elastic casing.', 520, 650, 62, '["/images/silk-scrunchie-set.webp"]'::jsonb, '["scrunchie", "silk", "hair", "accessories", "set", "no crease", "mulberry silk"]'::jsonb, '["Neutral Trio", "Jewel Trio"]'::jsonb, 1, 0),
  (20, 'satin-bonnet', 'Satin Sleep Bonnet', 'haircare', 'Sleep Care', 'A double-layer satin bonnet with a wide soft-elastic band that stays on through the night without pressing a line into your forehead. Keeps a blow-dry and reduces morning frizz. One size, adjustable.', 450, NULL, 54, '["/images/satin-bonnet.webp"]'::jsonb, '["bonnet", "satin", "hair", "sleep", "cap", "frizz", "night care"]'::jsonb, '["Ivory", "Maroon", "Black"]'::jsonb, 0, 0),
  (21, 'trendy-claw-clips', 'Trendy Claw Clips — Pair', 'haircare', 'Clips', 'Two large matte claw clips with a strong steel spring — they actually hold thick hair up through a working day. Marbled acetate finish in tortoise and ivory, no visible seam lines.', 380, 460, 76, '["/images/trendy-claw-clips.webp"]'::jsonb, '["claw clip", "hair clip", "accessories", "trendy", "matte", "pair"]'::jsonb, '["Tortoise & Ivory", "Maroon & Black"]'::jsonb, 1, 0),
  (22, 'heatless-curler-straightener-set', 'Mini Straightener & Heatless Curler Set', 'haircare', 'Styling', 'A travel-size ceramic mini straightener paired with a satin heatless curling rod. Use the rod overnight for soft curls with no heat damage, and the straightener for edges and fringe touch-ups. Dual voltage, with a heat-safe pouch.', 1450, 1850, 22, '["/images/heatless-curler-straightener-set.webp"]'::jsonb, '["straightener", "heatless curler", "styling", "hair", "set", "travel", "mini"]'::jsonb, '["Ivory", "Rose Gold"]'::jsonb, 0, 0),
  (23, 'anti-tarnish-ring-set', 'Anti-Tarnish Ring Set — 4 Pieces', 'fashion', 'Jewellery', 'Four stacking rings in 18k-gold-plated stainless steel — a plain band, a twisted band, a pearl solitaire and a fine cubic zirconia eternity. Anti-tarnish and water-safe, so they survive wudu and washing up without going green.', 690, 890, 48, '["/images/anti-tarnish-ring-set.webp"]'::jsonb, '["ring", "anti tarnish", "jewellery", "gold plated", "set", "stainless steel", "fashion"]'::jsonb, '["Size 6", "Size 7", "Size 8"]'::jsonb, 1, 0),
  (24, 'anti-tarnish-bracelet', 'Anti-Tarnish Chain Bracelet', 'fashion', 'Jewellery', 'A fine flat-link chain bracelet in gold-plated stainless steel with a lobster clasp and a 2 cm extender. Anti-tarnish, hypoallergenic, and light enough to layer under a watch.', 540, NULL, 56, '["/images/anti-tarnish-bracelet.webp"]'::jsonb, '["bracelet", "anti tarnish", "jewellery", "chain", "gold plated", "fashion"]'::jsonb, '["Gold", "Silver"]'::jsonb, 0, 0),
  (25, 'pearl-drop-earrings', 'Pearl Drop Earrings', 'fashion', 'Jewellery', 'Freshwater pearl drops on a gold-plated hook with a silicone stopper so they sit forward rather than slumping. Understated enough for work, bright enough for a wedding.', 480, 620, 60, '["/images/pearl-drop-earrings.webp"]'::jsonb, '["earrings", "pearl", "jewellery", "drop", "gold plated", "wedding", "fashion"]'::jsonb, '["Gold", "Silver"]'::jsonb, 0, 0),
  (26, 'jhumka-earrings', 'Oxidised Jhumka Earrings', 'fashion', 'Jewellery', 'Classic oxidised-silver-finish jhumka with a bead fringe and a light hollow dome — full-looking without dragging on the earlobe. Pairs with both a saree and a kurti.', 590, NULL, 44, '["/images/jhumka-earrings.webp"]'::jsonb, '["jhumka", "earrings", "oxidised", "jewellery", "traditional", "eid", "fashion"]'::jsonb, '["Silver Oxidised", "Antique Gold"]'::jsonb, 0, 0),
  (27, 'layered-necklace', 'Layered Pendant Necklace', 'fashion', 'Jewellery', 'A two-strand necklace — a short cable chain with a tiny cubic zirconia pendant over a longer plain chain — pre-linked so the layers never tangle. Gold-plated anti-tarnish steel.', 620, 780, 42, '["/images/layered-necklace.webp"]'::jsonb, '["necklace", "layered", "pendant", "jewellery", "anti tarnish", "gold plated"]'::jsonb, '["Gold", "Silver"]'::jsonb, 0, 0),
  (28, 'anklet-pair', 'Anti-Tarnish Anklet — Pair', 'fashion', 'Jewellery', 'A pair of fine anklets with small bell charms in anti-tarnish gold-plated steel. Adjustable clasp fits most ankles, and the charms are soft enough not to jingle loudly.', 450, NULL, 50, '["/images/anklet-pair.webp"]'::jsonb, '["anklet", "pair", "jewellery", "anti tarnish", "charm", "fashion"]'::jsonb, '["Gold", "Silver"]'::jsonb, 0, 0),
  (29, 'canvas-tote-bag', 'Heavy Canvas Tote Bag', 'fashion', 'Bags', 'A 12 oz cotton canvas tote with reinforced shoulder straps, an inner zip pocket and a flat base that lets it stand up on its own. Fits a 14-inch laptop, a water bottle and a tiffin box. Machine washable.', 690, 850, 58, '["/images/canvas-tote-bag.webp"]'::jsonb, '["tote bag", "canvas", "bag", "everyday", "laptop", "lifestyle", "washable"]'::jsonb, '["Ivory", "Charcoal", "Maroon"]'::jsonb, 1, 0),
  (30, 'mini-purse-card-holder', 'Mini Purse & Card Holder', 'fashion', 'Bags', 'A slim vegan-leather card holder with six card slots, a note sleeve and a snap coin pouch — sized to slip into the front pocket of a tote. Stitched edges, no raw lining.', 520, NULL, 64, '["/images/mini-purse-card-holder.webp"]'::jsonb, '["purse", "card holder", "wallet", "mini", "vegan leather", "fashion"]'::jsonb, '["Maroon", "Tan", "Black"]'::jsonb, 0, 0),
  (31, 'polarised-sunglasses', 'Polarised Sunglasses', 'gifts', 'Accessories', 'UV400 polarised lenses in a lightweight acetate frame with spring hinges. Cuts road and water glare properly rather than just darkening. Supplied with a hard case and a microfibre cloth.', 890, 1150, 34, '["/images/polarised-sunglasses.webp"]'::jsonb, '["sunglasses", "polarised", "uv400", "accessories", "gift", "unisex"]'::jsonb, '["Black", "Tortoise"]'::jsonb, 0, 0),
  (32, 'fashion-watch', 'Minimal Fashion Watch', 'gifts', 'Accessories', 'A 34 mm slim quartz watch with an ivory sunray dial, thin baton markers and a mesh steel strap that adjusts without tools. 3 ATM water resistant — safe in rain, not for swimming.', 1450, 1850, 26, '["/images/fashion-watch.webp"]'::jsonb, '["watch", "fashion", "minimal", "accessories", "gift", "quartz", "steel"]'::jsonb, '["Gold Mesh", "Silver Mesh"]'::jsonb, 1, 0),
  (33, 'mini-crossbody-bag', 'Mini Crossbody Bag', 'gifts', 'Bags', 'A structured mini crossbody in quilted vegan leather with a detachable chain-and-strap combination, so it works as a shoulder bag or a clutch. Fits a phone, a lipstick and a card holder.', 980, NULL, 30, '["/images/mini-crossbody-bag.webp"]'::jsonb, '["crossbody", "bag", "mini", "quilted", "gift", "fashion", "clutch"]'::jsonb, '["Maroon", "Black", "Cream"]'::jsonb, 0, 0),
  (34, 'slim-wallet', 'Slim Bifold Wallet', 'gifts', 'Accessories', 'A genuine-grain bifold with eight card slots, two note compartments and an RFID-blocking lining. Slim enough for a back pocket without the bulge.', 750, NULL, 40, '["/images/slim-wallet.webp"]'::jsonb, '["wallet", "bifold", "rfid", "gents", "gift", "accessories", "leather"]'::jsonb, '["Brown", "Black"]'::jsonb, 0, 0),
  (35, 'makeup-pouch', 'Quilted Makeup Pouch', 'gifts', 'Makeup Tools', 'A quilted satin pouch with a wipe-clean waterproof lining and a wide chunky zip that opens flat so you can actually see what is inside. Holds a full daily kit.', 420, 520, 68, '["/images/makeup-pouch.webp"]'::jsonb, '["makeup pouch", "quilted", "waterproof", "organizer", "gift", "travel"]'::jsonb, '["Ivory", "Maroon", "Sage"]'::jsonb, 0, 0),
  (36, 'makeup-brush-set', 'Makeup Brush Set — 12 Pieces', 'gifts', 'Makeup Tools', 'Twelve synthetic-bristle brushes covering face and eye, with tapered ferrules and matte handles. Synthetic fibres pick up less product and wash clean in one go. Includes a standing holder.', 890, 1150, 36, '["/images/makeup-brush-set.webp"]'::jsonb, '["brush set", "makeup brush", "12 pcs", "beauty", "tools", "gift", "synthetic"]'::jsonb, '["Rose Gold", "Black"]'::jsonb, 1, 0),
  (37, 'beauty-blender-set', 'Beauty Blender Set — 4 Pieces', 'gifts', 'Makeup Tools', 'Four latex-free sponges — teardrop, flat-edge, mini and powder-puff — plus a vented drying case. The flat edge is the one that finally gets foundation under the eyes without streaking.', 350, NULL, 74, '["/images/beauty-blender-set.webp"]'::jsonb, '["beauty blender", "sponge", "makeup", "set", "latex free", "tools", "gift"]'::jsonb, '["4 Pieces"]'::jsonb, 0, 0),
  (38, 'makeup-organizer', 'Acrylic Makeup Organizer', 'gifts', 'Organisers', 'A clear acrylic organiser with a brush well, four lipstick tiers and a deep drawer on smooth runners. Heavy enough not to skid across a dressing table when you pull the drawer.', 1150, 1450, 24, '["/images/makeup-organizer.webp"]'::jsonb, '["makeup organizer", "acrylic", "storage", "dressing table", "gift", "organiser"]'::jsonb, '["Clear", "Smoke"]'::jsonb, 0, 0),
  (39, 'cosmetic-travel-bag', 'Cosmetic Travel Bag', 'gifts', 'Organisers', 'A hanging travel case with four zip compartments, a removable brush roll and a swivel hook for the back of a bathroom door. Folds down to the size of a paperback.', 680, NULL, 42, '["/images/cosmetic-travel-bag.webp"]'::jsonb, '["travel bag", "cosmetic", "hanging", "organizer", "gift", "travel"]'::jsonb, '["Ivory", "Maroon"]'::jsonb, 0, 0),
  (40, 'nail-care-set', 'Nail Care Set — 10 Tools', 'gifts', 'Grooming', 'Ten stainless-steel grooming tools — clippers, scissors, cuticle pusher, tweezers, file and more — in a snap-shut leatherette case. Mirror-polished so they do not rust in a humid bathroom.', 520, NULL, 46, '["/images/nail-care-set.webp"]'::jsonb, '["nail care", "manicure", "grooming", "set", "stainless steel", "gift", "tools"]'::jsonb, '["10 Tools"]'::jsonb, 0, 0),
  (41, 'facial-ice-roller', 'Facial Ice Roller', 'gifts', 'Beauty Tools', 'A gel-filled stainless roller you keep in the freezer — rolls out morning puffiness and calms heat rash in about a minute. Sealed head, no leaking, with a stand.', 450, 580, 52, '["/images/facial-ice-roller.webp"]'::jsonb, '["ice roller", "facial", "puffiness", "beauty tool", "gift", "cooling"]'::jsonb, '["Ivory", "Rose"]'::jsonb, 0, 0),
  (42, 'face-massage-tool', 'Rose Quartz Gua Sha & Roller', 'gifts', 'Beauty Tools', 'Genuine rose quartz gua sha stone and a double-ended face roller, both hand-finished so the edges glide instead of dragging. Use with a few drops of serum along the jaw and brow.', 590, NULL, 40, '["/images/face-massage-tool.webp"]'::jsonb, '["gua sha", "face roller", "rose quartz", "massage", "beauty tool", "gift"]'::jsonb, '["Rose Quartz", "Jade"]'::jsonb, 0, 0),
  (43, 'compact-mirror', 'Engraved Compact Mirror', 'gifts', 'Accessories', 'A double-sided compact — plain and 2x magnifying — in a brushed metal shell with an engraved border. Snaps shut firmly so it will not open inside a bag.', 320, NULL, 78, '["/images/compact-mirror.webp"]'::jsonb, '["compact mirror", "magnifying", "accessories", "gift", "metal", "pocket"]'::jsonb, '["Gold", "Rose Gold"]'::jsonb, 0, 0),
  (44, 'jewellery-organizer-box', 'Jewellery Organizer Gift Box', 'gifts', 'Organisers', 'A velvet-lined two-tier box with ring rolls, a necklace hook panel and a small mirror in the lid. Presentable enough to give as the gift itself.', 1250, 1550, 20, '["/images/jewellery-organizer-box.webp"]'::jsonb, '["jewellery box", "organizer", "velvet", "gift box", "storage", "gift"]'::jsonb, '["Ivory", "Maroon"]'::jsonb, 1, 0),
  (45, 'couple-bracelet-keychain-set', 'Couple Bracelet & Keychain Set', 'gifts', 'Couple Gifts', 'A matched pair — two anti-tarnish steel bracelets and two interlocking keychain halves, packed in a slim magnetic box with a blank card. The most-bought anniversary gift under ৳700.', 690, 850, 44, '["/images/couple-bracelet-keychain-set.webp"]'::jsonb, '["couple", "bracelet", "keychain", "set", "gift", "anniversary", "valentine"]'::jsonb, '["Gold & Silver", "Black & Steel"]'::jsonb, 0, 0),
  (46, 'gift-box-under-499', 'Gift Box Under ৳499', 'gifts', 'Gift Boxes', 'A ready-wrapped box on a strict budget that still looks considered: one roll-on perfume oil, one silk scrunchie and one compact mirror, on a maroon tray with a blank card. Nothing in it feels like filler.', 499, NULL, 60, '["/images/gift-box-under-499.webp"]'::jsonb, '["gift box", "under 499", "budget", "gift", "scrunchie", "roll on", "combo"]'::jsonb, '["Ivory Wrap", "Maroon Wrap"]'::jsonb, 1, 0),
  (47, 'gift-box-under-999', 'Gift Box Under ৳999', 'gifts', 'Gift Boxes', 'A fuller box at under a thousand: one attar, one water lip tint, a silk scrunchie and a pearl-drop earring pair, on a velvet tray with a ribbon and card. Our standard birthday answer.', 999, 1250, 48, '["/images/gift-box-under-999.webp"]'::jsonb, '["gift box", "under 999", "gift", "attar", "lip tint", "earrings", "combo", "birthday"]'::jsonb, '["Ivory Wrap", "Maroon Wrap"]'::jsonb, 1, 0),
  (48, 'eid-gift-box', 'Eid Gift Box', 'gifts', 'Gift Boxes', 'Built for Eid: a gents attar, bakhoor chips, a pair of oxidised jhumka and a dates-and-chocolate tin, packed in a deep maroon rigid box with a foiled crescent card.', 1890, 2350, 30, '["/images/eid-gift-box.webp"]'::jsonb, '["eid", "gift box", "attar", "bakhoor", "jhumka", "festival", "combo"]'::jsonb, '["Standard", "Premium"]'::jsonb, 1, 0),
  (49, 'valentine-gift-box', 'Valentine Gift Box', 'gifts', 'Gift Boxes', 'A rose-musk roll-on, a glossy lip oil, a couple keychain pair and a dried-rose sachet in a heart-embossed box. Shipped with the price slip removed on request.', 1290, NULL, 38, '["/images/valentine-gift-box.webp"]'::jsonb, '["valentine", "gift box", "roll on", "lip oil", "couple", "romantic", "combo"]'::jsonb, '["Classic", "Deluxe"]'::jsonb, 0, 0),
  (50, 'anniversary-gift-box', 'Anniversary Gift Box', 'gifts', 'Gift Boxes', 'One gents attar, one ladies roll-on, a layered pendant necklace and a pair of anti-tarnish bracelets — a two-person box rather than a single gift. Velvet tray, magnetic lid, blank card.', 2190, 2690, 22, '["/images/anniversary-gift-box.webp"]'::jsonb, '["anniversary", "gift box", "couple", "attar", "necklace", "bracelet", "combo"]'::jsonb, '["Standard", "Premium"]'::jsonb, 0, 0),
  (51, 'self-care-gift-box', 'Self-Care Gift Box', 'gifts', 'Gift Boxes', 'A quiet-evening box: sheet masks, a facial ice roller, the ceramide moisturiser, a satin bonnet and a body mist. For the friend who keeps looking after everyone else.', 1690, 2050, 32, '["/images/self-care-gift-box.webp"]'::jsonb, '["self care", "gift box", "sheet mask", "ice roller", "bonnet", "friendship", "combo"]'::jsonb, '["Standard", "Deluxe"]'::jsonb, 0, 0),
  (52, 'customizable-gift-box', 'Customizable Gift Box', 'gifts', 'Gift Boxes', 'Pick the box size, then message us on WhatsApp with the items you want inside and the name for the card — we assemble, wrap and photograph it before dispatch so you can approve it. Price shown is the box and wrapping; item costs are added to the invoice.', 450, NULL, 100, '["/images/customizable-gift-box.webp"]'::jsonb, '["customizable", "gift box", "custom", "personalised", "whatsapp", "build your own"]'::jsonb, '["Small Box", "Medium Box", "Large Box"]'::jsonb, 1, 0)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  collection = excluded.collection,
  description = excluded.description,
  price = excluded.price,
  compare_price = excluded.compare_price,
  stock = excluded.stock,
  images = excluded.images,
  tags = excluded.tags,
  variants = excluded.variants,
  featured = excluded.featured,
  is_combo = excluded.is_combo;

select setval(pg_get_serial_sequence('products', 'id'), coalesce((select max(id) from products), 1));

commit;
